// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQIviYTQd_d6Gf2P437By415beluyJPa8',
    appId: '1:87555698655:android:01cbdd1b638c68935e1e6a',
    messagingSenderId: '87555698655',
    projectId: 'kiraplik',
    storageBucket: 'kiraplik.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAGNmI576oul5ZD0YbhqUvCQM7XNk1pcU',
    appId: '1:87555698655:ios:67b665d96ac3a1fd5e1e6a',
    messagingSenderId: '87555698655',
    projectId: 'kiraplik',
    storageBucket: 'kiraplik.firebasestorage.app',
    androidClientId: '87555698655-ucd0o0tj9od53rrbsg97vfjaq93kvru3.apps.googleusercontent.com',
    iosClientId: '87555698655-0o0t06o53pf5pg7iv3v4upurktbr4hrg.apps.googleusercontent.com',
    iosBundleId: 'com.example.kitaplik',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6AYD7mgiQPVAQLRuP8zwsHWvdsuD4W7o',
    appId: '1:87555698655:web:23b41a5206f8ccf25e1e6a',
    messagingSenderId: '87555698655',
    projectId: 'kiraplik',
    authDomain: 'kiraplik.firebaseapp.com',
    storageBucket: 'kiraplik.firebasestorage.app',
    measurementId: 'G-04NE804RCF',
  );

}